### ISSUE TITLE
One section is missing.

### ISSUE THREAD

**Issue by RaminMammadzada** [Prabhakarzx/AlexAndPrabhakar-NYTimes-Clone#3] opened 2020-06-19 14:32 UTC
There should be social buttons and read the amount of comments button.
Your version: ![image](https://user-images.githubusercontent.com/4702114/85143568-967c1c80-b252-11ea-9273-842c65fe7be2.png)

In the original one:
![image](https://user-images.githubusercontent.com/4702114/85143764-d4794080-b252-11ea-8358-610f593973ad.png)

The location in the codebase: https://github.com/Prabhakarzx/AlexAndPrabhakar-NYTimes-Clone/blob/5a142df4e76ba2c6484ff253185016424862f7ad/index.html#L275

**Comment by Prabhakarzx** [comment] 2020-06-19 15:07
Hi **@RaminMammadzada**,
I'm thankful and you pointed out this issue and helped to fix.
Thank You so much!
The issue is fixed now!

**Closed as completed by Prabhakarzx** 2020-06-19 15:07 UTC
